Portfolio/__init__.py
from flask import Flask


def create_app():
    app: Flask = Flask(__name__)
    app.config["SECRET_KEY"] = "Portfolio"

    from Portfolio.main.views import main
    app.register_blueprint(main, url_prefix="/")

    return app

Portfolio/main/views.py
from flask import Blueprint, render_template, send_file
# from flask import abort

from Portfolio.main.util import Repository, python_game, java_game, stats_site, store_management, portfolio, \
    repositories

main = Blueprint("main", __name__)

strengths = ["Fast Learner", "Good Team Player", "Goal Oriented", "Self Motivated"]

programming_languages = [
    ["Python", 3],
    ["Java", 3],
    ["HTML+CSS", 2],
    ["JavaScript", 1]
]

ALLOWED_EXTENSIONS = {"pdf"}


def allowed_file(filename: str):
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


@main.route("/", methods=["GET", "POST"])
def home():
    return render_template("home.html", projects=repositories, strengths=strengths, languages=programming_languages)


def create_project_route(repository: Repository, template_name):
    @main.route(repository.name, methods=["GET", "POST"], endpoint=f"{repository.name}_endpoint")
    def project_function():
        return render_template(
            template_name,
            project_name=repository.name,
            motivation=repository.motivation,
            about=repository.about,
            skills=repository.skills,
            languages=repository.languages
        )

    return project_function


@main.route("/download_resume", )
def download_resume():
    file_path = "static/theophilus-nenhanga-resume.pdf"
    # if not allowed_file(file_path):
    # abort(403)
    return send_file(file_path, as_attachment=True)


# Create routes for individual projects
python_game_route = create_project_route(python_game, "python_game.html")

java_game_route = create_project_route(java_game, "java_game.html")

stats_route = create_project_route(stats_site, "stats.html")

portfolio_route = create_project_route(portfolio, "portfolio.html")

store_management_route = create_project_route(store_management, "store_management.html")

# Register routes
main.add_url_rule("/projects/python-game", view_func=python_game_route, endpoint="python_game_endpoint")
main.add_url_rule("/projects/java-game", view_func=java_game_route, endpoint="java_game_endpoint")
main.add_url_rule("/projects/stats", view_func=stats_route, endpoint="stats_endpoint")
main.add_url_rule("/projects/portfolio", view_func=portfolio_route, endpoint="portfolio_endpoint")
main.add_url_rule("/projects/store-management", view_func=store_management_route, endpoint="store_management_endpoint")

Portfolio/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Theophilus N Nenhanga"/>
    <meta name="description" content="A portfolio showcasing Theophilus Nyasha Nenhanga's Programming projects."/>
    <title>Theophilus — Portfolio</title>

    {% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
    {% endblock stylesheet %}
    {% block script %}
    <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"></script>
    {% endblock script %}

    <!--Roboto-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">

    <!--Lato-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100&display=swap"
          rel="stylesheet">

    <!--Roboto Mono-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@100;200;300;400;500;600&display=swap"
          rel="stylesheet">

</head>

<body>

{% block body %}{% endblock body %}

<div class="footer-grid">
    <div class="center-flex">
        <a href="https://www.linkedin.com/in/theophilus-nenhanga-539b921b9/" target="_blank">
            <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-linkedin"
                 viewBox="0 0 16 16">
                <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
            </svg>
        </a>
    </div>


    <div class="center-flex">
        <button class="back-to-top-button" id="backToTopButton">Back To Top</button>
    </div>

    <div class="center-flex">
        <a href="https://github.com/TeeEnnEnn">
            <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-github"
                 viewBox="0 0 16 16">
                <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
            </svg>
        </a>
    </div>

</div>

<div>
    <footer>
        <span>Made by Me! Theophilus N Nenhanga</span>
    </footer>
</div>

</body>
</html>

Portfolio/templates/home.html
{% extends "base.html" %}

{% block body %}

<main>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='newStyles.css') }}">

    <section class="main-header">

        <div id="warningMessage">
            <p>Screen size too low. Please view this site on a larger screen</p>
        </div>

        <div class="" id="spacer"></div>
        <div class="hero">
            <h2 class="main-text">Hey there! I'm</h2>
            <h1 class="main-text">Theophilus<br>Nenhanga</h1>
            <h3 class="main-text">Welcome to my portfolio website<br>You'll learn a bit more about me<br>and what I have
                been working on</h3>
        </div>
        <div class="navbar">
            <a class="navbar-list-item" href="#profile">Profile</a>
            <a class="navbar-list-item" href="#projects">Projects</a>
            <a class="navbar-list-item" href="#knowledge">Knowledge Base</a>
            <a class="navbar-list-item" href="#next">What's Next</a>
        </div>
        <div></div>

        <div class="down-arrow">
            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-arrow-down"
                 viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                      d="M8 1a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L7.5 13.293V1.5A.5.5 0 0 1 8 1z"/>
            </svg>
        </div>

    </section>
    <div class="heading-pill" id="profile">
        <h3 class="divider-text">Profile</h3>
    </div>

    <div class="profile-grid">
        <div>
            <img class="about-image" src="{{ url_for('static', filename='face.jpg') }}" alt="A picture of Theophilus">
        </div>

        <div class="text-pill">
            <p class="pill-text-title">Who I Am</p>
            <p class="pill-text-p">
                Hey there, I'm Theophilus Nenhanga. Thank you for visiting my site. I'm a young developer hoping to one
                day may a difference with my code.
                I am currently studying at the University of Saskatchewan pursuing a bachelor's degree in Computer
                Science with a minor in Statistics.
                <br><br>
                When I am not writing code or being studious I'm most probably watching some sci-fi movie, playing a
                video game or reading something random online. I love thinking creatively and would like to
                work in an environment that allows me to make use of my creative mind.
            </p>
        </div>
    </div>

    <div class="download-grid">
        <div class="text-pill">
            <p class="pill-text-p">Have a look at my resume and see what else I have been up to!</p>
        </div>
        <div>
            <form action="{{ url_for('main.download_resume') }}">
                <button class="button" type="submit" id="download-button">Download Resume</button>
            </form>
        </div>
    </div>

    <div class="heading-pill" id="projects">
        <h3 class="divider-text">Projects</h3>
    </div>

    <div class="project-grid">
        {% for project in projects %}
        <div class="text-pill">
            <p class="pill-text-subtitle">{{ project.name }}</p>
            <p class="pill-text-subtitle">{{ project.date }}</p>
            <p class="pill-text-subtitle">{% for lang in project.languages %} {{ lang }} {% endfor %}</p>
            <p class="pill-text-subtitle">{{ project.description }}</p>

            <div class="button-link-grid">

                <a href="{{ project.link }}" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor"
                         class="bi bi-github"
                         viewBox="0 0 16 16">
                        <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                    </svg>
                </a>

                <a href="{{ project.learn_more }}">
                    <button class="button" type="button">Learn More</button>
                </a>

            </div>
        </div>
        {% endfor %}
    </div>

    <div class="heading-pill" id="knowledge">
        <h3 class="divider-text">Knowledge Base</h3>
    </div>

    <div class="quarter-grid">
        <div class="center-flex">
            <p class="pill-text-title">1 Bar</p>
            <p class="pill-text-p">Beginner Level</p>
            <p class="pill-text-p">Basic understanding of the language. Not confident enough to create standalone
                projects in the language</p>
        </div>

        <div class="center-flex">
            <p class="pill-text-title">2 Bars</p>
            <p class="pill-text-p">Lower Intermediate</p>
            <p class="pill-text-p">Moderate understanding of the language. Can comfortably use it to create projects,
                albeit simple projects</p>
        </div>

        <div class="center-flex">
            <p class="pill-text-title">3 Bars</p>
            <p class="pill-text-p">Upper Intermediate</p>
            <p class="pill-text-p">Deep understanding of the language. Knowledge of data structures and algorithms. Can
                comfortably create moderately complex projects</p>
        </div>

        <div class="center-flex">
            <p class="pill-text-title">4 Bars</p>
            <p class="pill-text-p">Advanced</p>
            <p class="pill-text-p">Understands inner workings of language and has achieved an expert level mastery that
                is shown through multiple complex projects</p>
        </div>

    </div>

    <div class="knowledge-grid">
        {% for language in languages %}
        <div class="text-pill">
            <p class="pill-text-p">{{ language[0] }}</p>
        </div>

        {% if language[1] == 1 %}
        <div class="slider-container">
            <div class="slider-one"></div>
            <div class="slider-container first"></div>
            <div class="slider-container second"></div>
            <div class="slider-container third"></div>
        </div>
        {% endif %}

        {% if language[1] == 2 %}
        <div class="slider-container">
            <div class="slider-two"></div>
            <div class="slider-container first"></div>
            <div class="slider-container second"></div>
            <div class="slider-container third"></div>
        </div>
        {% endif %}

        {% if language[1] == 3 %}
        <div class="slider-container">
            <div class="slider-three"></div>
            <div class="slider-container first"></div>
            <div class="slider-container second"></div>
            <div class="slider-container third"></div>
        </div>
        {% endif %}

        {% if language[1] == 4 %}
        <div class="slider-container">
            <div class="slider-four"></div>
            <div class="slider-container first"></div>
            <div class="slider-container second"></div>
            <div class="slider-container third"></div>
        </div>
        {% endif %}

        {% endfor %}
    </div>

    <div class="heading-pill" id="next">
        <h3 class="divider-text">What's Next</h3>
    </div>

    <div class="next-grid">
        <div class="text-pill">
            <p class="pill-text-title">What's Next</p>
            <p class="pill-text-p">
                I aim to continue to strengthen my knowledge of the key fundamentals of programming focussing my
                attention on Java and Python.
                I also hope to improve on my weaknesses wherever possible
                <br>
                <br>
                I hope to soon learn C# and apply my knowledge of the language in game development with Unity and
                windows software development with .NET
            </p>
        </div>

        <div class="text-pill">
            <p class="pill-text-title">Strengths</p>
            <div class="center-flex-list">
                <ul>
                    {% for strength in strengths %}
                    <li class="pill-text-p">{{ strength }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>


</main>

{% endblock body %}

Portfolio/templates/java_game.html
{% extends "project_base.html" %}

Portfolio/templates/portfolio.html
{% extends "project_base.html" %}

Portfolio/templates/project_base.html
{% extends "base.html" %}

{% block body %}

<div class="banner">
    <button onclick="goBack()" class="banner-button" type="button">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left"
             viewBox="0 0 16 16">
            <path fill-rule="evenodd"
                  d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
        </svg>
        <text>back</text><!--I am using this so I can use space around within the button -->
    </button>

    <div class="banner-list">
        <a href="/#profile" class="banner-list-button">Profile</a>
        <a href="/#projects" class="banner-list-button">Projects</a>
        <a href="/#knowledge" class="banner-list-button">Knowledge</a>
        <a href="/#next" id="firstBannerItem" class="banner-list-button">What's Next</a>
    </div>

    <div class="hamburger-menu">
        <button class="banner-button" type="button" id="hamburger-button">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list"
                 viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                      d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
            </svg>
        </button>
        <div class="hamburger-flyout invisible" id="hamburger-flyout">
            <div class="flyout-list">
                <a href="/#profile" class="banner-list-button">Profile</a>
                <a href="/#projects" id="projects" class="banner-list-button">Projects</a>
                <a href="/#knowledge" class="banner-list-button">Knowledge</a>
                <a href="/#next" class="banner-list-button">What's Next</a>
            </div>

        </div>
    </div>


</div>

<div class="heading-pill">
    <h3 class="divider-text">{{ project_name }}</h3>
</div>

<div class="half-grid">
    <div class="text-pill">
        <p class="pill-text-title">Motivation</p>
        <p class="pill-text-p">
            {{ motivation }}
        </p>
    </div>

    <div class="text-pill">
        <p class="pill-text-title">About the project</p>
        <p class="pill-text-p">
            {{ about }}
        </p>
    </div>
</div>

<div class="profile-grid">
    <div class="text-pill">
        <p class="pill-text-title">Languages Used</p>
        {% for language in languages %}
        <p class="pill-text-p">{{ language }}</p>
        {% endfor %}
    </div>
    <div class="text-pill">
        <p class="pill-text-title">Skills Utilised</p>
        {% for skill in skills %}
        <p class="pill-text-p">{{ skill }}</p>
        {% endfor %}
    </div>
</div>
{% endblock body %}

Portfolio/templates/python_game.html
{% extends "project_base.html" %}

Portfolio/templates/stats.html
{% extends "project_base.html" %}

Portfolio/templates/store_management.html
{% extends "project_base.html" %}